
spring.datasource.url=jdbc:mysql://localhost:3306/order_db
spring.datasource.username=root
spring.datasource.password=SAmyukthaa!@1232003

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
